### ISSUE TITLE
UI: Colorspace radio buttons to navigation-style button row

### ISSUE THREAD

**Issue by alkasm** [shaun-sweet/image-processing-ui#1]
Currently the colorspace selector is a radio button. We need to move this to a row of (non-radio) buttons, but that act like radio buttons---only one able to be selected at a time.

**Comment by shaun-sweet** [comment]
This will probably require some research by me in order to figure out the best route.  Although I suspect keeping them as radio buttons and just styling that is the best route.  Can explore checkboxes if theres a good reason.
