### ISSUE TITLE
Slider min/max values should change based on colorspace selected.

### ISSUE THREAD

**Issue by alkasm** [shaun-sweet/image-processing-ui#10]
Currently every slider ranges from 0 to 100. Need to update to allow values from 0 to 255 by default, and change depending on the colorspace selected. See the `README.md` for the appropriate values for each colorspace.

Also need to update the python script once this is completed to stop scaling the values from the 0 to 100 input.

**Comment by alkasm** [comment]
Python script has been updated to accept the correct values as described in `README.md`. See #14.

**Comment by shaun-sweet** [comment]
https://github.com/shaun-sweet/image-processing-ui/commit/a59ce44d47f22aa257a31185fdf341f88fae83ea
