### ISSUE TITLE
Update JS to work with two image output Python scripts

### ISSUE THREAD

**Issue by alkasm** [shaun-sweet/image-processing-ui#14]
Updated multiple features on python scripts and in branch [feature/two-image-outputs](https://github.com/shaun-sweet/image-processing-ui/tree/feature/two-image-outputs)
The changes are as follows:

1. `cspaceIO.py` expects *two* destination paths, `maskPath` and `maskedPath` and writes to both image paths; further, we need to display both.

**Use `.png` files for output paths!**

Example usage:

    python3 cspaceIO.py '{"paths":
        {"srcPath":"input/test.jpg",
        "maskPath":"output/test.png",
        "maskedPath":"output/test2.png"},
    "cspaceLabel":"BGR",
    "sliderPos":[50,100,50,100,50,100]}'

**Comment by shaun-sweet** [comment]
Changed the label for the output path of the file

**Comment by shaun-sweet** [comment]
donezo
