### ISSUE TITLE
Remove render button

### ISSUE THREAD

**Issue by alkasm** [shaun-sweet/image-processing-ui#17]
Eventually it would be nice to automagically render upon release of a slider or when a user enters a number into the input field, and when a user drops a new image into the window. The render button isn't a big hinderance but is overall unnecessary. Let's wait until we get some cleanup of the server first though because this will generate overall more images.

**Comment by shaun-sweet** [comment]
https://github.com/shaun-sweet/image-processing-ui/pull/37
