### ISSUE TITLE
Change choose file button to a dropzone

### ISSUE THREAD

**Issue by shaun-sweet** [shaun-sweet/image-processing-ui#6]
Dropzone that button!! Will look dope.

**Comment by shaun-sweet** [comment]
https://react-dropzone.js.org/

Make whole screen drop zone.  need to decide what kind of text for instructions

**Comment by alkasm** [comment]
Related: need to restrict to allowable filetypes. See the [filetype support](https://github.com/shaun-sweet/image-processing-ui/blob/master/README.md#filetype-support) section on `README.md`.

**Comment by alkasm** [comment]
Dropzone complete; see pull request #25.
