### ISSUE TITLE
Slider value display

### ISSUE THREAD

**Issue by alkasm** [shaun-sweet/image-processing-ui#9]
We need to have an `<input>` for slider values to display next to the sliders. User should be able to input values *or* change the slider and see the values changing in real-time.

**Comment by alkasm** [comment]
Check out the little box [here](https://codepen.io/seanstopnik/pen/CeLqA) which displays values. I dig the look of this.

**Comment by shaun-sweet** [comment]
@alkasm This should be good to go now!  Just needs to be styled but I'm gonna move on to other javascript stuff since I'll be the bottleneck there...

**Comment by shaun-sweet** [comment]
ok so now you can do 
```git fetch origin feature/slider-display-value```
```git checkout feature/slider-display-value```
and you should see my changes
